apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "prometheus-pve-exporter.fullname" . }}
  namespace: {{ .Values.scrapeConfigNamespace | default .Release.Namespace }}
  labels:
    {{- include "prometheus-pve-exporter.labels" . | nindent 4 }}
spec:
  jobName: pve
  staticConfigs:
    - targets: {{ .Values.scrapeTargets | toJson }}
  metricsPath: /pve
  params:
    module: ["default"]
    cluster: ["1"]
    node: ["1"]
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: {{ include "prometheus-pve-exporter.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
