apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pve
  namespace: {{ .Values.scrapeConfigNamespace | default .Release.Namespace }}
spec:
  jobName: pve
  staticConfigs:
    - targets:
      {{- .Values.scrapeTargets | toYaml | nindent 6 }}
  metricsPath: /pve
  params:
    module: [default]
    cluster: ["1"]
    node: ["1"]
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLAbels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: {{ include "prometheus-pve-exporter.fullname" . }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}
