name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current chart version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep '^version:' charts/promtheus-pve-exporter/Chart.yaml | cut -d' ' -f2)
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Get new chart version
        id: new-version
        run: |
          NEW_VERSION=$(grep '^version:' charts/promtheus-pve-exporter/Chart.yaml | cut -d' ' -f2)
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Chart version updated from ${{ steps.current-version.outputs.current-version }} to $NEW_VERSION" 