name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current chart version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep '^version:' charts/promtheus-pve-exporter/Chart.yaml | cut -d' ' -f2)
          echo "current-version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/github
            @semantic-release/npm
            @semantic-release/release-notes-generator
            @semantic-release/commit-analyzer
